### ISSUE TITLE
PEP8 styling not followed

### ISSUE THREAD

**Issue by vivekanand1101** [aedorado/CodeChef-Gitter#1]
Throughout the source code, [PEP8](https://www.python.org/dev/peps/pep-0008/) styling is not followed.
For example, it is advised to use 4 space indentation, which is definitely not followed here.
You can use [autopep8](https://pypi.python.org/pypi/autopep8). It helps :)

**Comment by vivekanand1101** [comment]
`while not OK` sounds better that `while OK is false`  ;)

**Comment by aedorado** [comment]
You're right about that Vivek.
Thanks for the tips. :)

**Comment by aedorado** [comment]
PEP8 is now done. You may close this issue.

**Comment by vivekanand1101** [comment]
:+1:
